### ISSUE TITLE
what's in the file assets?

### ISSUE THREAD

**Issue by nicoleandlili** [VPNht/android#4]
i get error after these method called,what's put int the file assets?
byte[] embeded = DigestUtils.md5(c.getAssets().open("openvpn"));
 byte[] installed = DigestUtils.md5(new FileInputStream(path));

 if (!path.setExecutable(true, true)) {
                    LogUtil.L("OpenvpnInstaller check !path.setExecutable(true, true).................................");
                    throw new IOException("Can't set executable flag");
                }

**Comment by se-bastiaan** [comment]
This doesn't seem part of the code of this app. https://github.com/VPNht/android/search?utf8=%E2%9C%93&q=OpenvpnInstaller&type=

Also, there is no such file called 'openvpn'.
